### ISSUE TITLE
split table and images

### ISSUE THREAD

**Issue by bahmansh** [jasonday/printThis#116]
I wanna split images and tables.
Now when a table is longer than page and dont fit table look like this.

![image](https://user-images.githubusercontent.com/19801131/27506119-1dd53178-58c7-11e7-86cf-640037694d84.png)

**Comment by oculus42** [comment]
This issue isn't specific to printThis. Page breaks in printing, especially in long tables, are [not well implemented](http://caniuse.com/#feat=css-page-break), no matter how you go about printing them.

This is no guarantee, but you might try adding a style something like this:

```CSS
tr {
  -webkit-page-break-inside: avoid; /* Chrome, Safari, Opera */
  page-break-inside: avoid;         /* Firefox */
  break-inside: avoid;              /* IE 10+ */
}
```

This suggestion is adapted from [a StackOverflow Answer about column breaks](https://stackoverflow.com/questions/7785374/how-to-prevent-column-break-within-an-element).
