### ISSUE TITLE
Possible to hide the page header and footer

### ISSUE THREAD

**Issue by marcusy3k** [jasonday/printThis#163]
Possible to remove or hide the page header (e.g. URL), and page footer (e.g. printing time)?

**Comment by oculus42** [comment]
There are no fully cross-browser methods to hide these elements, but in Chrome and Firefox, the following works:

```css
@media print {
  @page {
    margin: 0; 
  }
}
```

You may need to add some margin or padding to the `<body>` tag so you do not print all the way to the edges.
