### ISSUE TITLE
Is it possible to add Page Layout and Page Orientation Option? 

### ISSUE THREAD

**Issue by hiroksarker** [jasonday/printThis#168]

**Comment by oculus42** [comment]
Hi @hiroksarker There is a Paged Media Draft which proposes support for settings like this:

```css
@media print {
  @page { 
    size: A4 landscape;
  }
}
```

However, support for it is very limited. At this time, only Chrome supports the `size` property.

* [Can I Use: CSS Paged Media](https://caniuse.com/#feat=css-paged-media)
* [CSS Paged Media Module Draft - Size Property](https://www.w3.org/TR/css3-page/#page-size-prop)
